// srcs/svelte/src/components/Form/Form.svelte
<script>
  import {
    time,
    isValid,
    setTime,
    submitTime,
    isRequest
  } from './store';

  const handleChange = (event) => {
    setTime(event.target.value);
  }

  const handleSubmit = () => {
    submitTime($isValid, $time);
  }

  let isLoad;

  const unsubscribe = isRequest.subscribe(value => {
		isLoad = value;
	});

  $: buttonText = isLoad ? 'Proccesing' : 'Submit';

</script>

<div class="form">
  <input
    class:error={!$isValid}
    value={$time}
    on:input={handleChange}
  />

  {#if !$isValid}
    <span class="error-message">Invalid time format</span>
  {/if}

  <button
    disabled={isLoad}
    on:click={handleSubmit}
  >
    {buttonText}
  </button>
</div>

<style>
  .form {
    display: flex;
    flex-direction: column;
  }

  input {
    padding: 5px;
    outline: none;
  }

  button {
    margin-top: 20px;
    padding: 10px 0;
  }

  .error {
    border: 2px solid red;
  }

  .error-message {
    color: red;
  }
</style>

// srcs/vue-class/src/components/Form/Form.vue
<template>
  <div :class="$style.form">
    <input
      :class="[$style.input, { [$style.inputError]: !form.isValid }]"
      :value="form.time"
      @input="handleChange"
    />

    <span
      v-if="!form.isValid"
      :class="$style.errorMessage"
    >
      Invalid time format
    </span>

    <button
      :class="$style.button"
      :disabled="form.isRequestLoad"
      @click="sumbitTime"
    >
      {{buttonText}}
    </button>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { State, Action } from 'vuex-class';

import { IState } from './store/mutations';

const namespace: string = 'form';

@Component
export default class Form extends Vue {
  @State('form')
  form!: IState;

  @Action('setTime', { namespace })
  setTime!: (time: string) => void;

  @Action('sumbitTime', { namespace })
  sumbitTime!: (time: string) => void;

  get buttonText (): string {
    return this.form.isRequestLoad ? 'Processing' : 'Submit';
  }

  handleChange(event): void {
    this.setTime(event.target.value)
  }
}
</script>

<style lang="scss" module>
  .form {
    display: flex;
    flex-direction: column;
    max-width: 600px;
  }
  .button {
    margin-top: 10px;
    padding: 5px;
  }
  .input {
    padding: 5px;
    outline: none;
    border: 2px solid #666666;
  }
  .errorMessage {
    color: red;
    align-self: flex-start;
    margin-top: 5px;
  }
  .inputError {
    border-color: red;
  }
</style>
