// srcs/reactMobx/src/components/Form/Form.tsx
import React, { useCallback } from 'react';
import { observer } from 'mobx-react';
import { useStores } from '../../store/hooks';
import './styles.scss';

const Form = observer(() => {
  const { form } = useStores()

  const handleChange = useCallback((event: React.ChangeEvent<HTMLInputElement>): void => {
    form.setTime(event.target.value);
  }, [form])

  const handleClick = useCallback((): void => {
    form.setSubmitedTime(form.time);
  }, [form])

  return (
    <div className="form">
      <input
        value={form.time}
        onChange={handleChange}
        className={`input ${!form.isValid && 'input-error'}`}
        type="text"
      />

      {!form.isValid && <span className="error">Invalid time format</span>}

      <button
        className="button"
        onClick={handleClick}
        disabled={form.isRequest}
      >
        {form.isRequest ? 'Processing' : 'Submit'}
      </button>
    </div>
  );
});

export default Form;

// srcs/svelte/src/components/Form/Form.svelte
<script>
  import {
    time,
    isValid,
    setTime,
    submitTime,
    isRequest
  } from './store';

  const handleChange = (event) => {
    setTime(event.target.value);
  }

  const handleSubmit = () => {
    submitTime($isValid, $time);
  }

  let isLoad;

  const unsubscribe = isRequest.subscribe(value => {
		isLoad = value;
	});

  $: buttonText = isLoad ? 'Proccesing' : 'Submit';

</script>

<div class="form">
  <input
    class:error={!$isValid}
    value={$time}
    on:input={handleChange}
  />

  {#if !$isValid}
    <span class="error-message">Invalid time format</span>
  {/if}

  <button
    disabled={isLoad}
    on:click={handleSubmit}
  >
    {buttonText}
  </button>
</div>

<style>
  .form {
    display: flex;
    flex-direction: column;
  }

  input {
    padding: 5px;
    outline: none;
  }

  button {
    margin-top: 20px;
    padding: 10px 0;
  }

  .error {
    border: 2px solid red;
  }

  .error-message {
    color: red;
  }
</style>
