// srcs/reactMobx/src/App.tsx
let timeStart = performance.now()
import React from 'react';
import Form from './components/Form';
import TodoList from './components/TodoList';

class App extends React.Component {
  componentDidMount () {
    console.log("First render complete, time:", performance.now() - timeStart)
  }
  render () {
    return (
      <>
        <Form />
        <TodoList />
      </>
    );
  }
}

export default App;

// srcs/vue/src/App.vue
<template>
  <div id="app">
    <Form />
    <TodoList />
  </div>
</template>

<script lang="ts">
let timeStart = performance.now();
import Vue from 'vue';
import Form from './components/Form';
import TodoList from './components/TodoList';

export default Vue.extend({
  name: 'app',
  components: {
    Form,
    TodoList
  },
  mounted: function () {
    console.log("First render complete, time:", performance.now() - timeStart);
  }
});
</script>
