// srcs/reactMobx/src/App.tsx
let timeStart = performance.now()
import React from 'react';
import Form from './components/Form';
import TodoList from './components/TodoList';

class App extends React.Component {
  componentDidMount () {
    console.log("First render complete, time:", performance.now() - timeStart)
  }
  render () {
    return (
      <>
        <Form />
        <TodoList />
      </>
    );
  }
}

export default App;

// srcs/svelte/src/App.svelte
<script>
  let timeStart = performance.now();
  import '@babel/polyfill';
  import { onMount } from 'svelte';
  import Form from './components/Form';
  import TodoList from './components/TodoList';

  onMount(() => {
    console.log("First render complete, time:", performance.now() - timeStart)
  });
</script>

<div class="container">
  <Form />
  <TodoList />
</div>

<style>
  .container {
    width: 600px;
  }
</style>
